/*
 * blog.js
 * Generated by Geany 1.22
 * 
 * Author:	Edward Osorio S.
 * Date:	2014-06-20
 * Version:	1.0
 * Mail:	osorio.edd@gmail.com
 * 
 * Copyright 2014
 * 
 */

// 0.6.5 Ejercicios

$(document).ready(
	function(){
		var $blog = $('#blog');
		
		$blog.find('h3').on('click',
			function(e){
				e.preventDefault();
				var $h3 = $(this);
				var $p = $h3.next('p');
				$p.slideToggle();
				
				$h3.parent().siblings().find('p:visible').slideUp();
			}
		);
		
	}
);
