/*
 * navigation.js
 * Generated by Geany 1.22
 * 
 * Author:	Edward Osorio S.
 * Date:	2014-06-20
 * Version:	1.0
 * Mail:	osorio.edd@gmail.com
 * 
 * Copyright 2014
 * 
 */

// 0.6.5 Ejercicios
$(document).ready(
	function(){
		var $list = $('#nav li');
		$list.on('hover',
			function(){
				$(this).toggleClass('hover');
				$(this).children('ul').slideToggle();
				//$(this).children('ul').fadeToggle();
			}
		);
	}
);
