/*
 * tabs.js
 * Generated by Geany 1.22
 * 
 * Author:	Edward Osorio S.
 * Date:	2014-06-19
 * Version:	1.0
 * Mail:	osorio.edd@gmail.com
 * 
 * Copyright 2014
 * 
 */

// Crear una Navegacion por pesta;as de los objetos 'div.module'
$(document).ready(
	function(){
		var $divs = $('div.module').hide();
		var $list = $('<ul/>').addClass('tabs').insertBefore($divs.eq(0));
		$divs.each(
			function(idx, el){
				var title = $(el).find('h2').html();
				var $tab = $('<li>' + title + '</li>');
				$list.append($tab);
				
				$tab.on('click',
					function(){
						$(el).show().siblings('.module').hide();
						$tab.addClass('current').siblings().removeClass('current');
					}
				);
			}
		);
		$divs.eq(0).show();
		$('ul.tabs li:first').addClass('current');
	}
);
